name: Build main Branche

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install pnpm -g
          pnpm install

      - name: Build
        run: 
          pnpm build

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: dist
